### ISSUE TITLE
All tabs are now the same color after latest Firefox update using custom theme

### ISSUE THREAD

**Issue by novanityneo** [easonwong-de/Adaptive-Tab-Bar-Colour#98] opened 2024-11-28 06:56 UTC
After the November 26th 2024 Firefox update, all tabs including the selected tab are the same color. And trying to adjust the tinting options changes other things. For example changing the toolbar tint changes the url bar instead.

**Comment by Scotty-Trees** [comment] 2024-12-04 03:52
Judging by some of the latest commits it looks like the dev is aware that the latest version of Firefox (v133) broke some UI elements and the add-on needs an overhaul to get working again. We just gotta be patient as they work to address the issue. As of v133 the add-on no longer replaces any colors for my Firefox, it's essentially borked, but I'm also using Firefox Gnome Theme as well so they may play a part. But I'm confident when a new version is released this will be address.

**Comment by CennoxX** [comment] 2024-12-05 08:07
> As of v133 the add-on no longer replaces any colors for my Firefox, it's essentially borked, but I'm also using Firefox Gnome Theme as well so they may play a part. But I'm confident when a new version is released this will be address.

We should create a second issue for this. I have the same problem, but only on one PC, the other works without problem.

**Comment by easonwong-de** [comment] 2024-12-06 08:26
@Scotty-Trees Indeed, the add-on is undergoing a big overhaul, at least internally. Yet, I couldn’t reproduce the issue you guys described @novanityneo, @Scotty-Trees, @CennoxX. I’ve tested on Firefox v133 & v134 with & without custom CSS theme, the colours are given to the browser UI correctly. Could you specify the platform and the CSS theme you are using?

**Comment by easonwong-de** [comment] 2024-12-06 08:45
On Firefox v134, the colour is indeed not given to the browser UI. I’m looking into this.

**Comment by Scotty-Trees** [comment] 2024-12-06 15:22
@easonwong-de thanks for the quick reply. I am currently on Firefox v133 on Fedora Gnome under Wayland, using the Firefox Gnome Theme ( https://github.com/rafaelmardojai/firefox-gnome-theme ) and that theme developer literally just released the easiest way to install the theme too via a flatpak from here: https://flathub.org/apps/dev.qwery.AddWater, which I've tested and used myself and works quite well. Perhaps maybe the Adaptive add-on is incompatible when using the Firefox Gnome Theme?

**Comment by easonwong-de** [comment] 2024-12-06 19:54
@Scotty-Trees Firefox Gnome Theme does overwrite theme colours given by ATBC. For example, the navbar has been given the colour of `#303030` (in dark mode) through `background: var(--gnome-headerbar-background) !important;` [(link)](https://github.com/rafaelmardojai/firefox-gnome-theme/blob/aa9b67045fcdec7ae045b36d7a41b36b3463b842/theme/parts/headerbar.css#L6) and `--gnome-headerbar-background: #303030;` [(link)](https://github.com/rafaelmardojai/firefox-gnome-theme/blob/aa9b67045fcdec7ae045b36d7a41b36b3463b842/theme/colors/dark.css#L33).

The optimal solution is for @rafaelmardojai to provide an ATBC-compatible version of CSS theme. Otherwise, additional CSS theme files should be added to overwrite the colours back.

**Comment by easonwong-de** [comment] 2024-12-24 06:54
I’m assuming it was the CSS theme that was causing the problem. Thus, I’ll close this issue for now.

If the theme colours are not given to Firefox correctly even without a CSS theme, feel free to reopen this issue.

**Closed by easonwong-de** 2024-12-24 06:54 UTC

**Comment by easonwong-de** [comment] 2025-04-19 18:14
@Scotty-Trees Hi, if you are still interested: someone actually made a supplement CSS theme to add support to firefox-gnome-theme (https://gist.github.com/eilx/2e1346472598ddac5e2ec20f40695dfe).
