### ISSUE TITLE
Favicon’s Dark/Light Variation Should Follow the Browser Instead of the System

### ISSUE THREAD

**Issue by cawa-93** [easonwong-de/Adaptive-Tab-Bar-Colour#56] opened 2023-07-05 18:21 UTC
My OS is Windows 11.
In OS theme is light. I open GitHub and status bar colored into dark. But the favicons are still used as a light theme. As a result, we have dark icons on a dark background.

Here is a picture. Three tabs from left to right: inactive, active and `:hover`
![зображення](https://github.com/easonwong-de/Adaptive-Tab-Bar-Color/assets/1662812/59500c43-40d4-4853-b136-e3c443302fc7)

As you can see github favicons is beraly visible.

But if I switch OS theme to dark favicons also swith to dark theme
![зображення](https://github.com/easonwong-de/Adaptive-Tab-Bar-Color/assets/1662812/04ae97c4-f3d0-4a26-a2f0-edb402c507aa)

**Comment by easonwong-de** [comment] 2023-07-05 18:26
This issue was brought up in #5. But it wasn’t the main issue at that time, so it was not tracked after the issue is closed. I’m glad that it gets brought up again.

**Comment by kud** [comment] 2024-11-09 12:29
I've got the same issue here:

![CleanShot 2024-11-09 at 12 29 00@2x](https://github.com/user-attachments/assets/8567d5b8-bc41-4a90-9c73-2a0fb72247d2)

**Comment by easonwong-de** [comment] 2024-12-24 06:19
I removed the “bug” tag because this is the intended behaviour of ATBC.

To make sure we are on the same page: GitHub’s website determines whether to use the dark or light version of its favicon based on the system’s OS settings, while keeping the navigation bar’s colour unchanged. In light mode, this results in the favicon having a colour very similar to the navigation bar. Since ATBC sets the navigation bar’s colour to match the tab bar, the favicon becomes hard to distinguish. This logic can be summarized as:

![atbc-github-situation](https://github.com/user-attachments/assets/d0c54cd4-5f18-40cf-9033-a5fab83bd9e3)

I may close this issue now, because:

1. Many websites design their favicons without considering the user’s UI colour, so situations like this can still occur even without ATBC.
2. ATBC only modifies Firefox’s theme, not the HTML, which includes the favicon in the header.

**Closed by easonwong-de** 2024-12-24 06:19 UTC
Labels: enhancement
